//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinical
    {
        public int clinicalID { get; set; }
        public string clinicalName { get; set; }
        public string clinicalEmail { get; set; }
        public int clinicalCollegateNumber { get; set; }
        public int jobID { get; set; }
        public int buildingID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Job Job { get; set; }
    }
}
