//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int scheduleDetailID { get; set; }
        public int scheduleID { get; set; }
        public string weekdayName { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public int dayNumber { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
